development:
  adapter: postgresql
  encoding: utf8
  database: piecemaker_v_0_5_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: piecemaker_v_0_5_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: piecemaker_v_0_5_production
  pool: 5
  username: 
  password:

